"""
HuggingFace Transformers backend — on-prem GPU/CPU inference.

Supported models:
    meta-llama/Llama-3.2-1B-Instruct   — test / CPU (~2 GB RAM)
    meta-llama/Llama-3.2-3B-Instruct   — ~6 GB VRAM
    meta-llama/Llama-3.1-8B-Instruct   — ~16 GB VRAM  (8-bit: ~8 GB)
    meta-llama/Llama-3.1-70B-Instruct  — multi-GPU / requires 4-bit

Installation::

    pip install "ai-guard[transformers]"

Usage::

    from ai_guard import LLMGuard

    guard = LLMGuard(
        use_llm=True,
        llm_backend="transformers",
        llm_model="meta-llama/Llama-3.1-8B-Instruct",
    )

8-bit / 4-bit quantization (VRAM savings)::

    guard = LLMGuard(
        use_llm=True,
        llm_backend="transformers",
        llm_model="meta-llama/Llama-3.1-8B-Instruct",
        llm_load_in_8bit=True,   # 16 GB → ~8 GB
    )

Environment variables:
    HF_TOKEN   — HuggingFace access token for gated models
"""

from __future__ import annotations

import logging
import threading
from typing import Any

from ai_guard.llm.backends.base import BaseLLMBackend, ProgressCallback

logger = logging.getLogger(__name__)


class TransformersBackend(BaseLLMBackend):
    """
    HuggingFace Transformers-based on-prem LLM backend.

    The model is loaded on the first ``complete_messages()`` call (lazy loading).
    Thread-safe: model loading is protected by a lock.

    Args:
        model:         HuggingFace model ID (e.g. ``"meta-llama/Llama-3.1-8B-Instruct"``).
        device_map:    ``"auto"`` for multi-GPU/CPU distribution (default),
                       ``"cpu"`` for CPU only.
        load_in_8bit:  bitsandbytes 8-bit quantization — reduces VRAM usage by ~half.
        load_in_4bit:  bitsandbytes 4-bit quantization — reduces VRAM usage by ~quarter.
        max_new_tokens: Maximum number of tokens to generate (default 512).
    """

    def __init__(
        self,
        model: str,
        *,
        device_map: str = "auto",
        load_in_8bit: bool = False,
        load_in_4bit: bool = False,
        max_new_tokens: int = 512,
    ) -> None:
        self._model_name = model
        self._device_map = device_map
        self._load_in_8bit = load_in_8bit
        self._load_in_4bit = load_in_4bit
        self._max_new_tokens = max_new_tokens
        self._pipeline: Any = None
        self._lock = threading.Lock()

    # ------------------------------------------------------------------
    # BaseLLMBackend interface
    # ------------------------------------------------------------------

    def complete(self, prompt: str, *, timeout: int = 60) -> str:
        """Send a plain-text prompt as a user message."""
        return self.complete_messages(
            [{"role": "user", "content": prompt}],
            timeout=timeout,
        )

    def complete_messages(self, messages: list[dict], *, timeout: int = 60) -> str:
        """Send chat messages to the model using the tokenizer chat template.

        Args:
            messages: ``[{"role": "system"|"user"|"assistant", "content": ...}, ...]``
            timeout:  Not used (no network timeout for local inference);
                      the parameter is kept for interface compatibility.

        Returns:
            The assistant response generated by the model (raw text).

        Raises:
            ValueError: If the model returns empty output or the pipeline fails.
        """
        pipe = self._get_pipeline()

        try:
            outputs = pipe(
                messages,
                max_new_tokens=self._max_new_tokens,
                do_sample=False,  # equivalent to temperature=0 — deterministic
                return_full_text=False,  # return only new tokens
            )
        except Exception as exc:
            raise ValueError(f"Model inference failed ({self._model_name}): {exc}") from exc

        if not outputs:
            raise ValueError(f"Model returned empty output: {self._model_name}")

        # Transformers pipeline output format:
        # [{"generated_text": "..." | [{"role":..., "content":...}]}]
        generated = outputs[0].get("generated_text", "")
        if isinstance(generated, list):
            # Chat format: return the content of the last message
            if not generated:
                raise ValueError(f"Model chat output is empty: {self._model_name}")
            last = generated[-1]
            if not isinstance(last, dict):
                raise ValueError(
                    f"Unexpected chat output format from {self._model_name}: "
                    f"expected dict, got {type(last).__name__}"
                )
            return last.get("content", "") or ""
        return str(generated)

    def list_models(self) -> list[str]:
        """Return the name of the loaded model."""
        return [self._model_name]

    def pull_model(
        self,
        model: str,
        *,
        on_progress: ProgressCallback | None = None,
    ) -> None:
        """Download the model from HuggingFace Hub.

        Args:
            model:       HuggingFace model ID (e.g. ``"meta-llama/Llama-3.1-8B-Instruct"``).
            on_progress: Progress callback (HF download does not provide detailed progress —
                         start and completion events are sent).

        Raises:
            ImportError:   If ``huggingface_hub`` is not installed.
            OSError:       If HF_TOKEN is missing for a gated model.
        """
        try:
            from huggingface_hub import snapshot_download
        except ImportError:
            raise ImportError(
                "'huggingface_hub' is required to download models.\n"
                "Install with: pip install huggingface_hub"
            ) from None

        logger.info("Downloading from HuggingFace Hub: %s", model)
        if on_progress:
            from ai_guard.llm.backends.base import PullProgress

            on_progress(PullProgress(status="downloading", completed=0, total=0))

        snapshot_download(repo_id=model)

        logger.info("Model downloaded: %s", model)
        if on_progress:
            from ai_guard.llm.backends.base import PullProgress

            on_progress(PullProgress(status="success", completed=1, total=1))

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    def _get_pipeline(self) -> Any:
        """Return the model pipeline; load it if not yet loaded (lazy, thread-safe)."""
        with self._lock:
            if self._pipeline is None:
                self._pipeline = self._load_pipeline()
                # Chat template check: if missing, the LLM may not understand the message format.
                tokenizer = getattr(self._pipeline, "tokenizer", None)
                if tokenizer is not None and not getattr(tokenizer, "chat_template", None):
                    logger.warning(
                        "Model %r tokenizer does not have a chat_template defined. "
                        "complete_messages() may produce unexpected results. "
                        "Use an Instruct/Chat-capable model (e.g. *-Instruct, *-chat).",
                        self._model_name,
                    )
        return self._pipeline

    def _load_pipeline(self) -> Any:
        """Create and return the transformers pipeline."""
        try:
            import torch
            from transformers import BitsAndBytesConfig, pipeline
        except ImportError:
            raise ImportError(
                "'transformers' and 'torch' are required for the Transformers backend.\n"
                "Install with: pip install 'ai-guard[transformers]'"
            ) from None

        logger.info("Loading Transformers model: %s", self._model_name)

        kwargs: dict[str, Any] = {
            "task": "text-generation",
            "model": self._model_name,
            "device_map": self._device_map,
            "dtype": torch.bfloat16,
        }

        if self._load_in_8bit:
            kwargs["quantization_config"] = BitsAndBytesConfig(load_in_8bit=True)
        elif self._load_in_4bit:
            kwargs["quantization_config"] = BitsAndBytesConfig(load_in_4bit=True)

        pipe = pipeline(**kwargs)
        logger.info("Transformers model ready: %s", self._model_name)
        return pipe
