"""Name pools for the ``surrogate`` action, one set per locale.

Short, common names that read as ordinary in each language. They are drawn
from at random for a value, so any real person sharing one of them is a
coincidence the documentation warns about; there is no way to make a plausible
name that nobody has.
"""

from __future__ import annotations

SUPPORTED_LOCALES: tuple[str, ...] = ("en", "tr", "de", "fr")

FIRST_NAMES: dict[str, tuple[str, ...]] = {
    "en": (
        "Alex",
        "Amelia",
        "Ava",
        "Ben",
        "Chloe",
        "Daniel",
        "Ella",
        "Ethan",
        "Grace",
        "Harry",
        "Isla",
        "Jack",
        "James",
        "Lily",
        "Liam",
        "Lucy",
        "Mia",
        "Noah",
        "Oliver",
        "Olivia",
        "Oscar",
        "Poppy",
        "Ruby",
        "Samuel",
        "Sophie",
        "Thomas",
        "William",
        "Zoe",
        "Henry",
        "Emily",
    ),
    "tr": (
        "Ahmet",
        "Ayşe",
        "Ali",
        "Aylin",
        "Berk",
        "Burcu",
        "Cem",
        "Ceren",
        "Defne",
        "Deniz",
        "Ece",
        "Emre",
        "Elif",
        "Fatma",
        "Gizem",
        "Hakan",
        "İrem",
        "Kaan",
        "Kerem",
        "Melis",
        "Mehmet",
        "Merve",
        "Murat",
        "Mustafa",
        "Nazlı",
        "Onur",
        "Selin",
        "Serkan",
        "Zeynep",
        "Yusuf",
    ),
    "de": (
        "Anna",
        "Ben",
        "Clara",
        "David",
        "Emma",
        "Felix",
        "Finn",
        "Hannah",
        "Jonas",
        "Julia",
        "Katharina",
        "Lara",
        "Lena",
        "Leon",
        "Lukas",
        "Marie",
        "Max",
        "Mia",
        "Niklas",
        "Paul",
        "Sarah",
        "Sophie",
        "Tim",
        "Tobias",
        "Laura",
        "Moritz",
        "Nele",
        "Jan",
        "Lisa",
        "Noah",
    ),
    "fr": (
        "Adrien",
        "Alice",
        "Camille",
        "Chloé",
        "Clara",
        "Émile",
        "Emma",
        "Gabriel",
        "Hugo",
        "Inès",
        "Jade",
        "Jules",
        "Léa",
        "Léo",
        "Louis",
        "Louise",
        "Lucas",
        "Manon",
        "Mathis",
        "Nathan",
        "Noé",
        "Océane",
        "Paul",
        "Raphaël",
        "Sarah",
        "Théo",
        "Thomas",
        "Zoé",
        "Arthur",
        "Lina",
    ),
}

LAST_NAMES: dict[str, tuple[str, ...]] = {
    "en": (
        "Adams",
        "Baker",
        "Bennett",
        "Brooks",
        "Carter",
        "Collins",
        "Cooper",
        "Davies",
        "Evans",
        "Fisher",
        "Foster",
        "Graham",
        "Harris",
        "Hayes",
        "Hughes",
        "Jenkins",
        "Kelly",
        "Lewis",
        "Mason",
        "Mitchell",
        "Morgan",
        "Murphy",
        "Owen",
        "Parker",
        "Reed",
        "Russell",
        "Shaw",
        "Turner",
        "Walker",
        "Wright",
    ),
    "tr": (
        "Acar",
        "Akın",
        "Arslan",
        "Aydın",
        "Çelik",
        "Demir",
        "Doğan",
        "Erdoğan",
        "Güneş",
        "Kara",
        "Kaya",
        "Kılıç",
        "Koç",
        "Korkmaz",
        "Kurt",
        "Öztürk",
        "Polat",
        "Şahin",
        "Şimşek",
        "Taş",
        "Tekin",
        "Turan",
        "Ünal",
        "Uysal",
        "Yalçın",
        "Yıldırım",
        "Yıldız",
        "Yılmaz",
        "Aksoy",
        "Bulut",
    ),
    "de": (
        "Bauer",
        "Becker",
        "Braun",
        "Fischer",
        "Hartmann",
        "Hoffmann",
        "Jung",
        "Klein",
        "Koch",
        "Krause",
        "Krüger",
        "Lange",
        "Lehmann",
        "Meyer",
        "Neumann",
        "Peters",
        "Richter",
        "Schäfer",
        "Schmidt",
        "Schneider",
        "Schulz",
        "Schwarz",
        "Vogel",
        "Wagner",
        "Weber",
        "Werner",
        "Winkler",
        "Wolf",
        "Zimmermann",
        "Frank",
    ),
    "fr": (
        "Bernard",
        "Blanc",
        "Bonnet",
        "Chevalier",
        "Dubois",
        "Durand",
        "Fontaine",
        "Fournier",
        "Garnier",
        "Girard",
        "Lambert",
        "Laurent",
        "Lefebvre",
        "Legrand",
        "Leroy",
        "Martin",
        "Mercier",
        "Michel",
        "Morel",
        "Moreau",
        "Petit",
        "Richard",
        "Robert",
        "Roux",
        "Rousseau",
        "Simon",
        "Thomas",
        "Vincent",
        "Faure",
        "Garcia",
    ),
}

# Two words and a legal form, so an organisation reads as one in its language.
ORG_WORDS: dict[str, tuple[tuple[str, ...], tuple[str, ...], tuple[str, ...]]] = {
    "en": (
        ("Northwind", "Bluewater", "Redwood", "Silverline", "Highland", "Crescent", "Harbor"),
        ("Systems", "Logistics", "Partners", "Analytics", "Industries", "Holdings", "Media"),
        ("Ltd", "Inc", "LLC", "Group", "Co"),
    ),
    "tr": (
        ("Kuzey", "Mavi", "Anadolu", "Ege", "Marmara", "Doğu", "Yıldız"),
        ("Lojistik", "Teknoloji", "Enerji", "Yazılım", "Sigorta", "Gıda", "İnşaat"),
        ("A.Ş.", "Ltd. Şti.", "Holding", "Grup"),
    ),
    "de": (
        ("Nord", "Rhein", "Alpen", "Hansa", "Elbe", "Berg", "Süd"),
        ("Logistik", "Technik", "Energie", "Software", "Bau", "Handel", "Medien"),
        ("GmbH", "AG", "KG", "Gruppe"),
    ),
    "fr": (
        ("Nord", "Atlantique", "Alpine", "Loire", "Provence", "Azur", "Lumière"),
        ("Logistique", "Technologies", "Énergie", "Conseil", "Industries", "Médias", "Services"),
        ("SARL", "SAS", "SA", "Groupe"),
    ),
}

# RFC 2606 reserves these; mail to them goes nowhere.
EMAIL_DOMAINS: tuple[str, ...] = ("example.com", "example.net", "example.org")
